version: '3'

networks:
  lemah:
    name: "lemah"
    driver: "bridge"

services:
  backend:
    build:
      context: "./mahPong"
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    networks:
      - lemah
  
  db:
    image: postgres:15-alpine
    restart: always
    expose:
      - 5432
    networks:
      - lemah
    environment:
      POSTGRES_PASSWORD: 123123123
      POSTGRES_USER: postgres
      POSTGRES_DB: lemah